version: '3.7'

services:
  db:
    container_name: "db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    expose:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306"
    # setting some env vars to create the DB
    environment:
      LANG: C.UTF-8
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "ya"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "1876Ggfq"

    # we mount a data volume to make sure we don't lose data
    volumes:
      - mysql_data:/var/lib/mysql
    command: --local-infile
  api:
    container_name:  "api"
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
      - "443:443"
    # we are depending on the mysql backend
    depends_on:
      - db
    # We mount the working dir into the container, handy for development
    # This is what makes the hot reloading work inside of a Docker container
    volumes:
      - .:/app/

networks:
  default:
volumes:
  mysql_data: